#docker run -d -p 5000:5432 --name postgre_docker_manager -e POSTGRES_DB=docker_manager -e POSTGRES_PASSWORD=root -e POSTGRES_USER=root postgres:16
spring.application.name=docker_manager
server.port=9000

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://localhost:5000/docker_manager

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.docker.compose.enabled=false